name       : libbaseencode
version    : 1.0.9
release    : 2
source     :
    - https://github.com/paolostivanin/libbaseencode/archive/v1.0.9.tar.gz : a183d7cf30d931b2a078d6f0ef64616b71ab26f9258e5f4e191778c7ace7175d
license    : Apache-2.0
component  : programming.library
summary    : Library written in C for encoding and decoding data using base32 or base64 (RFC-4648)
description: |
    Library written in C for encoding and decoding data using base32 or base64 (RFC-4648)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
